apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cloudyfluke-com
spec:
  secretName: cloudyfluke-com-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: cloudyfluke.com
  dnsNames:
  - "*.cloudyfluke.com"
  - "cloudyfluke.com"
