apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-crds
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gitops/cert-manager-crds
    repoURL: https://github.com/cloudyfluke/homelab
    targetRevision: HEAD
