apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: ingress-nginx
      repoURL: https://kubernetes.github.io/ingress-nginx
      targetRevision: "4.12.0"
      helm:
        valueFiles:
          - $values/gitops/ingress-nginx/values.yaml
    - repoURL: https://github.com/cloudyfluke/homelab
      targetRevision: HEAD
      ref: values
