apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-vip
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: kube-vip
      repoURL: https://kube-vip.github.io/helm-charts
      targetRevision: "0.6.6"
      helm:
        valueFiles:
          - $values/gitops/kube-vip/values.yaml
    - repoURL: https://github.com/cloudyfluke/homelab
      targetRevision: HEAD
      ref: values
