apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
spec:
  destination:
    namespace: pihole
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: pihole
      repoURL: https://mojo2600.github.io/pihole-kubernetes
      targetRevision: "2.27.0"
      helm:
        releaseName: pihole-cne
        valueFiles:
          - $values/gitops/pihole/values.yaml
    - repoURL: https://github.com/cloudyfluke/homelab
      targetRevision: HEAD
      ref: values
