apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - base/certificate.yaml
  - base/argo-cd-ui-ingress.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/refs/tags/v2.14.2/manifests/ha/install.yaml

patches:
  - path: overlays/homelab/argocd-cmd-params-cm.yaml
  - path: overlays/homelab/argocd-server-service.yaml
  - path: overlays/homelab/argocd-rbac-cm.yaml
  - path: overlays/homelab/cmp-plugin.yaml
  - path: overlays/homelab/argocd-repo-server-deployment.yaml
