apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-cd-cert
spec:
  secretName: cloudyfluke-com-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: cd.cloudyfluke.com
  dnsNames:
  - cd.cloudyfluke.com

